### ISSUE TITLE
Failed building on VisualStudio for Mac

### ISSUE THREAD

**Issue by kekyo** [kekyo/CenterCLR.RelaxVersioner#13]
Moved from NMeCab PR: https://github.com/komutan/NMeCab/pull/35

@komutan VisualStudio for Macでビルドするときに、MSBuildのフルログを取ることはできませんか？（かなり長くなる筈です）

VisualStudio for Windowsで言うところのこの設定です:

![image](https://user-images.githubusercontent.com/6181948/115137640-361c5e00-a062-11eb-9fd8-dbf878aaf839.png)

**Comment by komutan** [comment]
このように設定して、IDEに表示されるログを採取してみました。お役に立ちますでしょうか。

<img width="960" alt="スクリーンショット 2021-04-18 16 57 46" src="https://user-images.githubusercontent.com/5524222/115138468-539ff680-a067-11eb-806d-803b5eebd3e1.png">
<img width="962" alt="スクリーンショット 2021-04-18 16 56 56" src="https://user-images.githubusercontent.com/5524222/115138469-56025080-a067-11eb-9a1f-d6d9dcaf41d3.png">

[RelaxVersioner_building.log](https://github.com/kekyo/CenterCLR.RelaxVersioner/files/6330731/RelaxVersioner_building.log)

**Comment by kekyo** [comment]
MEMO: https://github.com/libgit2/libgit2sharp/blob/df3b22a754ef56da8d7e3c330ce2d783c2b7982e/LibGit2Sharp/GlobalSettings.cs#L319

**Comment by kekyo** [comment]
MEMO:
https://github.com/kekyo/CenterCLR.RelaxVersioner/blob/6ed62a2bbc3a6e37ac7588462f54ee61b33ee9bf/CenterCLR.RelaxVersioner.Core/Utilities.cs#L85

* monoの場合に回避する
  * monoの判定方法（どこかでやったかも）
* または例外を無視する？
* 代わりにアセンブリのパスを出力する？
* NativeLibraryPathを他で使っていなかったかどうか？
* UTの方法（CIを考えるとすぐにはできないかも）

**Comment by kekyo** [comment]
ログの該当位置: 6134

```
RelaxVersioner[2.3.0]: LibGit2SharpException=Querying the native hint path is only supported on .NET Framework and .NET Core platforms, Unknown exception occurred,   at LibGit2Sharp.GlobalSettings.get_NativeLibraryPath () [0x00011] in <a12e7c49fcdb4cdb8ae14cdefe2ac344>:0 
      at RelaxVersioner.Utilities+<>c__DisplayClass5_0.<OpenRepository>b__0 (System.String path) [0x00012] in <874fd88d9f3949bca2b4fc982df4eadf>:0 
      at RelaxVersioner.Utilities.TraversePathToRoot[T] (System.String candidatePath, System.Func`2[T,TResult] action) [0x00011] in <874fd88d9f3949bca2b4fc982df4eadf>:0 
      at RelaxVersioner.Utilities.OpenRepository (RelaxVersioner.Logger logger, System.String candidatePath) [0x0000d] in <874fd88d9f3949bca2b4fc982df4eadf>:0 
      at RelaxVersioner.Processor.Run (RelaxVersioner.ProcessorContext context) [0x00052] in <874fd88d9f3949bca2b4fc982df4eadf>:0 
      at RelaxVersioner.Program.Main (System.String[] args) [0x00233] in <f53d3a7d2c404f87847aa861ab97042f>:0 
```

**Comment by kekyo** [comment]
@komutan 修正してみました。バージョン 2.3.1 ですが、手元にmacが無いので、何か別の問題が発生したら教えて下さい。パッケージはmygetに上げてあるので、使う場合はこのような nuget.config をNMeCabのルートに置けば、参照できるようになると思います:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="kekyo" value="https://www.myget.org/F/kekyo/api/v2" />
  </packageSources>
</configuration>
```

**Comment by komutan** [comment]
@kekyo 
確認できました。伝えて頂いたnuget.configを置いてバージョン 2.3.1 に更新でき、問題なくビルドできて、パックすることも、全てをVS for Mac上で実行できました。ありがとうございました。

**Comment by kekyo** [comment]
確認ありがとうございます! 明日か明後日にはnuget にpublishします

**Comment by kekyo** [comment]
2.3.2でnugetに正式にPublishしました。
