### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by BioBox** [kekyo/CenterCLR.RelaxVersioner#6]
It's quite a shame that there isn't any documentation for this project yet, as I feel that having it would be quite nice.

I've made a wiki on my own fork which you can view [here](https://github.com/BioBox/CenterCLR.RelaxVersioner/wiki). Let me know what you think.

It's still a work in progess, and I'd like to make it more complete, but GitHub doesn't support pull-requests for wikis, so if you want me to help you document this on your own fork then you would have to make me a contributor.

**Comment by kekyo** [comment]
That's nice!! 👍 

Should you make the contents on the RelaxVersioner repository? For example we can make docs directory at the root and place pointer into the README. It's functionally for PR.

I think we will switch to github.io if the content have larger.

**Comment by BioBox** [comment]
Okay. I made the documentation as part of the repository itself.

You can take a look at it on [my fork](https://github.com/BioBox/CenterCLR.RelaxVersioner).
Keep in mind that these files describe the import functionality that I've made, so you should probably merge that before incorporating the docs.

**Comment by kekyo** [comment]
Happy new year! and thanks read the your docs. And I understand the import feature and please wait it merge soon ;)

**Comment by BioBox** [comment]
I'm glad to hear it, and happy new year. :smile:

**Comment by kekyo** [comment]
@biobox Your docs commit now merged 1abdd626719f92b9c9de14bf4a0bf2d61724cee0
The RelaxVersioner is fixed F#'s import limitation. I removed the suggestion from the sentence.
